### ISSUE TITLE
Destination directory /etc/sysconfig does not exist

### ISSUE THREAD

**Issue by peavers** [linux-system-roles/timesync#117]
Hey, 

Brand new to Ansible so sorry if this is just me being dumb but trying to run this and getting the following error: 

```
TASK [linux-system-roles.timesync : Generate chronyd sysconfig file] ***************************************************************************************************************************************
fatal: [192.168.0.129]: FAILED! => {"changed": false, "checksum": "c86b9165a42f39a42071825554f79870abaee593", "msg": "Destination directory /etc/sysconfig does not exist"}
```

This is just using the example configuration from the readme. 

```
- hosts: servers
  vars:
    timesync_ntp_servers:
      - hostname: 0.europe.pool.ntp.org
        iburst: yes
      - hostname: 1.europe.pool.ntp.org
        iburst: yes
      - hostname: 2.europe.pool.ntp.org
        iburst: yes
  roles:
    - linux-system-roles.timesync
 ```

Have I done something wrong here?
