### ISSUE TITLE
chrony.conf ubuntu crash

### ISSUE THREAD

**Issue by MrOffline77** [linux-system-roles/timesync#162]
The timesync role places the chrony.conf into /etc for each OS. Ubuntu (DEBIAN) expects the config in the /etc/chrony/ directory.  Should be handled inside /tasks/main.yml as os specific variable.

```
- name: Generate chrony.conf file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    backup: true
    mode: 0644
  notify: restart {{ 'chronyd' if timesync_mode == 1 else 'timemaster' }}
  when:
    - timesync_mode != 2
    - timesync_ntp_provider == 'chrony'
    - "'chrony' in ansible_facts.packages"
```
